### ISSUE TITLE
How to send messages

### ISSUE THREAD

**Issue by GJ2511** [coma/react-socket#3]
Any event or callback to send message

**Comment by GJ2511** [comment]
@coma Any updates??

**Comment by coma** [comment]
Hi there!

You can get the socket.io instance using [this](https://github.com/coma/react-socket/blob/0.1.3/src/socket.js#L30) and start sending messages with [emit](http://socket.io/docs/).

I want to give some fresh air to this project so any suggestion would be very appreciated.

**Comment by GJ2511** [comment]
Ok Thx @coma
